### PR TITLE
Fix project url and feature request link in README

### PR DESCRIPTION
**Pull request by Chewsterchew**
The project website url doesn't even work, so that was fixed.
The Feature Request link worked, but it's easier to cut out the middle man and just redirect to issues in the right org.

### CODE REVIEW

**Comment by garrettw** [comment]
There's an extra `/` in the project webpage URL now.

**Comment by streerwise702** [comment]
Hey I do apologize I’m trying to get this person off my account they took over it

**Comment by streerwise702** [comment]
Did you to pull 702-820-8096 off my account if you can I’m trying to do it but I keep getting kicked back

**Comment by streerwise702** [comment]
Academy to know ASAP

**Comment by garrettw** [comment]
@streerwise702 If you're having issues with your account you need to contact GitHub about it. This is not the place for it, as CodeHub is merely an app that lets you use GitHub on your phone. Besides, this is a pull request, not a support thread.

**Comment by kincaider** [comment]
I just got to the point where I’m going to go took a shower and I got to go to the gym and I have to go to the gym and I have to go to the gym and I have to go to the gym and I have to go get some food and I will see what you guys have been thinking about and I’m not going anywhere but I’m not going to go get food I have a couple more minutes I have a few things to go get you guys can I have some stuff for dinner tomorrow I will let him go to work tomorrow I have a good night I will be home soon and I’ll see if you guys have a chance I will talk with them later I have to get them tomorrow I have a lot to say I don’t want you guys and you have a lot going to come over tomorrow night and then I’ll come back and see what you want me and you guys can get together for dinner tonight or do I have something else for dinner I want you guys and I’ll come get it tomorrow night

**Comment by Chewsterchew** [comment]
@kincaider nice

**Comment by kincaider** [comment]
CodeHub - A client for Github

**Comment by thedillonb** [comment]
Thanks for the changes @Chewsterchew

**Comment by Chewsterchew** [comment]
Hey sorry to bother, what kind of PR has the "Chewsterchew commited with thedillonb"?

**Pull request merged**
