### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by seewise1983**

### CODE REVIEW

**Comment by jenihena1111** [comment]
ヽ(⌐■_■)ノ♪♬

**Comment by Stewart4554** [comment]
😀

**Comment by moonsmoon** [comment]
H

**Comment by RogerG6** [comment]
i don't know what's going on? my english is not well




| |
RogerG6
|
|
邮箱：rogerg6@163.com
|

Signature is customized by Netease Mail Master

On 11/21/2018 14:00, moonsmoon wrote:

H

**Comment by spycomet** [comment]
haha!!!!

**Comment by xinghub** [comment]
啥




| |
安卓工程师17602137912
邮箱：xingzydd@163.com
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:08, RogerG6 wrote:
i don't know what's going on? my english is not well




| |
RogerG6
|
|
邮箱：rogerg6@163.com
|

Signature is customized by Netease Mail Master

On 11/21/2018 14:00, moonsmoon wrote:

H

**Comment by xinghub** [comment]
what are you doing？




| |
安卓工程师17602137912
邮箱：xingzydd@163.com
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:10, spycomet wrote:

haha!!!!

**Comment by sheldon-s** [comment]
我们再用邮箱聊天？？发自我的iPhone------------------ Original ------------------From: xinghub  <notifications@github.com>Date: Wed,Nov 21,2018 2:12 PMTo: CodeHubApp/CodeHub <CodeHub@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [CodeHubApp/CodeHub] Develop (#482)啥




| |
安卓工程师17602137912
邮箱：xingzydd@163.com
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:08, RogerG6 wrote:
i don't know what's going on? my english is not well




| |
RogerG6
|
|
邮箱：rogerg6@163.com
|

Signature is customized by Netease Mail Master

On 11/21/2018 14:00, moonsmoon wrote:

H

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CodeHubApp/CodeHub","title":"CodeHubApp/CodeHub","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/CodeHubApp/CodeHub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xinghub in #482: 啥\n\n\n\n\n| |\n安卓工程师17602137912\n邮箱：xingzydd@163.com\n|\n\n签名由 网易邮箱大师 定制\n\nOn 11/21/2018 14:08, RogerG6 wrote:\ni don't know what's going on? my english is not well\n\n\n\n\n| |\nRogerG6\n|\n|\n邮箱：rogerg6@163.com\n|\n\nSignature is customized by Netease Mail Master\n\nOn 11/21/2018 14:00, moonsmoon wrote:\n\nH\n\n—\nYou are receiving this because you are subscribed to this thread.\nReply to this email directly, view it on GitHub, or mute the thread.\n\n—\nYou are receiving this because you are subscribed to this thread.\nReply to this email directly, view it on GitHub, or mute the thread."}],"action":{"name":"View Pull Request","url":"https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440545748"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440545748",
"url": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440545748",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [CodeHubApp/CodeHub] Develop (#482)",
"sections": [
{
"text": "",
"activityTitle": "**xinghub**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@xinghub",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"CodeHubApp/CodeHub\",\n\"issueId\": 482,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440545748"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 344323389\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by wwt960702** [comment]
什么鬼，邮箱响个不停

**Comment by huangxionging** [comment]
哪个傻B乱发的




On 11/21/2018 14:12, xinghub wrote:
what are you doing？




| |
安卓工程师17602137912
邮箱：xingzydd@163.com
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:10, spycomet wrote:

haha!!!!

**Comment by xinghub** [comment]
都被推送了




| |
安卓工程师17602137912
邮箱：xingzydd@163.com
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:16, 黄雄 wrote:
哪个傻B乱发的




On 11/21/2018 14:12, xinghub wrote:
what are you doing？




| |
安卓工程师17602137912
邮箱：xingzydd@163.com
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:10, spycomet wrote:

haha!!!!

**Comment by frinck** [comment]
炸啦我擦

**Comment by RogerG6** [comment]
我也不知道，蛋疼




| |
RogerG6
|
|
邮箱：rogerg6@163.com
|

Signature is customized by Netease Mail Master

On 11/21/2018 14:17, wwt960702 wrote:

什么鬼，邮箱响个不停

**Comment by yellowprogramer** [comment]
What happened？ is the code hub wrong ？

**Comment by RogerG6** [comment]
关键是，为什么我能看到大家的信息，我们在群里吗




| |
RogerG6
|
|
邮箱：rogerg6@163.com
|

Signature is customized by Netease Mail Master

On 11/21/2018 14:17, RogerG6 wrote:
我也不知道，蛋疼




| |
RogerG6
|
|
邮箱：rogerg6@163.com
|

Signature is customized by Netease Mail Master

On 11/21/2018 14:17, wwt960702 wrote:

什么鬼，邮箱响个不停

**Comment by miloSone** [comment]
不觉得这样很无聊吗 , 


| |
宋鑫磊
|
|
inoubliable_s@163.com
|
签名由网易邮箱大师定制
On 11/21/2018 14:17，黄雄<notifications@github.com> wrote：
哪个傻B乱发的




On 11/21/2018 14:12, xinghub wrote:
what are you doing？




| |
安卓工程师17602137912
邮箱：xingzydd@163.com
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:10, spycomet wrote:

haha!!!!

**Comment by Liuqiutian** [comment]
鬼知道，邮箱一直叫个不停




| |
刘秋田
大数据有限公司  - 
开发工程师
17778027374
邮箱：lqtjava@163.com
574687732
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:18, sheldon-s wrote:
我们再用邮箱聊天？？发自我的iPhone------------------ Original ------------------From: xinghub <notifications@github.com>Date: Wed,Nov 21,2018 2:12 PMTo: CodeHubApp/CodeHub <CodeHub@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [CodeHubApp/CodeHub] Develop (#482)啥




| |
安卓工程师17602137912
邮箱：xingzydd@163.com
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:08, RogerG6 wrote:
i don't know what's going on? my english is not well




| |
RogerG6
|
|
邮箱：rogerg6@163.com
|

Signature is customized by Netease Mail Master

On 11/21/2018 14:00, moonsmoon wrote:

H

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CodeHubApp/CodeHub","title":"CodeHubApp/CodeHub","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/CodeHubApp/CodeHub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xinghub in #482: 啥\n\n\n\n\n| |\n安卓工程师17602137912\n邮箱：xingzydd@163.com\n|\n\n签名由 网易邮箱大师 定制\n\nOn 11/21/2018 14:08, RogerG6 wrote:\ni don't know what's going on? my english is not well\n\n\n\n\n| |\nRogerG6\n|\n|\n邮箱：rogerg6@163.com\n|\n\nSignature is customized by Netease Mail Master\n\nOn 11/21/2018 14:00, moonsmoon wrote:\n\nH\n\n—\nYou are receiving this because you are subscribed to this thread.\nReply to this email directly, view it on GitHub, or mute the thread.\n\n—\nYou are receiving this because you are subscribed to this thread.\nReply to this email directly, view it on GitHub, or mute the thread."}],"action":{"name":"View Pull Request","url":"https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440545748"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440545748",
"url": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440545748",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [CodeHubApp/CodeHub] Develop (#482)",
"sections": [
{
"text": "",
"activityTitle": "**xinghub**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@xinghub",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"CodeHubApp/CodeHub\",\n\"issueId\": 482,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440545748"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 344323389\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by xinghub** [comment]
都是GitHub账号，有人在测试




| |
安卓工程师17602137912
邮箱：xingzydd@163.com
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:18, sheldon-s wrote:
我不知道我自己订阅了什么，为什么会发生这个情况？大家都是干啥的？发自我的iPhone------------------ Original ------------------From: xinghub <notifications@github.com>Date: Wed,Nov 21,2018 2:14 PMTo: CodeHubApp/CodeHub <CodeHub@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [CodeHubApp/CodeHub] Develop (#482)what are you doing？




| |
安卓工程师17602137912
邮箱：xingzydd@163.com
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:10, spycomet wrote:

haha!!!!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CodeHubApp/CodeHub","title":"CodeHubApp/CodeHub","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/CodeHubApp/CodeHub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xinghub in #482: what are you doing？\n\n\n\n\n| |\n安卓工程师17602137912\n邮箱：xingzydd@163.com\n|\n\n签名由 网易邮箱大师 定制\n\nOn 11/21/2018 14:10, spycomet wrote:\n\nhaha!!!!\n\n—\nYou are receiving this because you are subscribed to this thread.\nReply to this email directly, view it on GitHub, or mute the thread."}],"action":{"name":"View Pull Request","url":"https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440546370"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440546370",
"url": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440546370",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [CodeHubApp/CodeHub] Develop (#482)",
"sections": [
{
"text": "",
"activityTitle": "**xinghub**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@xinghub",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"CodeHubApp/CodeHub\",\n\"issueId\": 482,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440546370"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 344323389\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Liweijun900** [comment]
你们好烦啊！！！！！

发自我的 iPhone

**Comment by xinghub** [comment]
不知道啊




| |
安卓工程师17602137912
邮箱：xingzydd@163.com
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:20, RogerG6 wrote:
关键是，为什么我能看到大家的信息，我们在群里吗




| |
RogerG6
|
|
邮箱：rogerg6@163.com
|

Signature is customized by Netease Mail Master

On 11/21/2018 14:17, RogerG6 wrote:
我也不知道，蛋疼




| |
RogerG6
|
|
邮箱：rogerg6@163.com
|

Signature is customized by Netease Mail Master

On 11/21/2018 14:17, wwt960702 wrote:

什么鬼，邮箱响个不停

**Comment by xinghub** [comment]
什么鬼啊




| |
安卓工程师17602137912
邮箱：xingzydd@163.com
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:20, xinghub wrote:
不知道啊




| |
安卓工程师17602137912
邮箱：xingzydd@163.com
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:20, RogerG6 wrote:
关键是，为什么我能看到大家的信息，我们在群里吗




| |
RogerG6
|
|
邮箱：rogerg6@163.com
|

Signature is customized by Netease Mail Master

On 11/21/2018 14:17, RogerG6 wrote:
我也不知道，蛋疼




| |
RogerG6
|
|
邮箱：rogerg6@163.com
|

Signature is customized by Netease Mail Master

On 11/21/2018 14:17, wwt960702 wrote:

什么鬼，邮箱响个不停

**Comment by Liuqiutian** [comment]
他们不上班在瞎搞




| |
刘秋田
大数据有限公司  - 
开发工程师
17778027374
邮箱：lqtjava@163.com
574687732
|

签名由 网易邮箱大师 定制

On 11/21/2018 14:29, CylonRichard wrote:
他们是在干嘛……




发自网易邮箱 iPhone 版
On 11/21/2018 14:25, jinglebelly wrote:

Give me a break

**Comment by L1nzhe** [comment]
从现在开始 谁再发邮件谁是狗




            
            
                
                    
                            
                                
                            
                            
                                374677998
                            
                    
                        
                            
                                    邮箱：374677998@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 11/21/2018 14:29, CylonRichard wrote: 他们是在干嘛……




发自网易邮箱 iPhone 版
On 11/21/2018 14:25, jinglebelly wrote:

Give me a break

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CodeHubApp/CodeHub","title":"CodeHubApp/CodeHub","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/CodeHubApp/CodeHub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@CylonRichard in #482: 他们是在干嘛……\n\n\n\n\n发自网易邮箱 iPhone 版\nOn 11/21/2018 14:25, jinglebelly wrote:\n\nGive me a break\n\n—\nYou are receiving this because you are subscribed to this thread.\nReply to this email directly, view it on GitHub, or mute the thread."}],"action":{"name":"View Pull Request","url":"https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440550545"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440550545",
"url": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440550545",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [CodeHubApp/CodeHub] Develop (#482)",
"sections": [
{
"text": "",
"activityTitle": "**CylonRichard**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@CylonRichard",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"CodeHubApp/CodeHub\",\n\"issueId\": 482,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440550545"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 344323389\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by miloSone** [comment]
可以停止了吗 , 别再回复抄送了 , 谢谢


| |
宋鑫磊
|
|
inoubliable_s@163.com
|
签名由网易邮箱大师定制
On 11/21/2018 14:32，Herrycao<notifications@github.com> wrote：
冷静啊 哥们

從我的 iPhone 傳送

**Comment by Liweijun900** [comment]
上github取消邮箱推送就好。
详情自行百度，我刚查到。现在去取消。
真心受不了。


发自我的 iPhone

**Comment by GoesyWang** [comment]
whats the f**k


2018-11-21 





发件人：RogerG6 <notifications@github.com>
发送时间：2018-11-21 14:09
主题：Re: [CodeHubApp/CodeHub] Develop (#482)
收件人："CodeHubApp/CodeHub"<CodeHub@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

i don't know what's going on? my english is not well




| |
RogerG6
|
|
邮箱：rogerg6@163.com
|

Signature is customized by Netease Mail Master

On 11/21/2018 14:00, moonsmoon wrote:

H

**Comment by duansq1999** [comment]
哈哈哈我也收到了，突然发现好多邮件！

薛定谔的死亡猫

**Comment by BenDJoaner** [comment]
再发我就退群了

BenDJoaner

________________________________
收件人: duansq <notifications@github.com>
发送时间: 星期三, 十一月 21, 2018 5:51 下午
收件人: CodeHubApp/CodeHub
抄送: Subscribed
主题: Re: [CodeHubApp/CodeHub] Develop (#482)

哈哈哈我也收到了，突然发现好多邮件！

薛定谔的死亡猫

> 在 2018年11月21日，下午2:18，sheldon-s <notifications@github.com> 写道：
>
> 我们再用邮箱聊天？？发自我的iPhone------------------ Original ------------------From: xinghub <notifications@github.com>Date: Wed,Nov 21,2018 2:12 PMTo: CodeHubApp/CodeHub <CodeHub@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [CodeHubApp/CodeHub] Develop (#482)啥
>
>
>
>
> | |
> 安卓工程师17602137912
> 邮箱：xingzydd@163.com
> |
>
> 签名由 网易邮箱大师 定制
>
> On 11/21/2018 14:08, RogerG6 wrote:
> i don't know what's going on? my english is not well
>
>
>
>
> | |
> RogerG6
> |
> |
> 邮箱：rogerg6@163.com
> |
>
> Signature is customized by Netease Mail Master
>
> On 11/21/2018 14:00, moonsmoon wrote:
>
> H
>
> ―
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
> ―
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
> ―You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CodeHubApp/CodeHub","title":"CodeHubApp/CodeHub","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/CodeHubApp/CodeHub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xinghub in #482: 啥\n\n\n\n\n| |\n安卓工程师17602137912\n邮箱：xingzydd@163.com\n|\n\n签名由 网易邮箱大师 定制\n\nOn 11/21/2018 14:08, RogerG6 wrote:\ni don't know what's going on? my english is not well\n\n\n\n\n| |\nRogerG6\n|\n|\n邮箱：rogerg6@163.com\n|\n\nSignature is customized by Netease Mail Master\n\nOn 11/21/2018 14:00, moonsmoon wrote:\n\nH\n\n―\nYou are receiving this because you are subscribed to this thread.\nReply to this email directly, view it on GitHub, or mute the thread.\n\n―\nYou are receiving this because you are subscribed to this thread.\nReply to this email directly, view it on GitHub, or mute the thread."}],"action":{"name":"View Pull Request","url":"https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440545748"}}}
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440545748",
> "url": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440545748",
> "name": "View Pull Request"
> },
> "description": "View this Pull Request on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> },
> {
> "@type": "MessageCard",
> "@context": "http://schema.org/extensions",
> "hideOriginalBody": "false",
> "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
> "title": "Re: [CodeHubApp/CodeHub] Develop (#482)",
> "sections": [
> {
> "text": "",
> "activityTitle": "**xinghub**",
> "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
> "activitySubtitle": "@xinghub",
> "facts": [
>
> ]
> }
> ],
> "potentialAction": [
> {
> "name": "Add a comment",
> "@type": "ActionCard",
> "inputs": [
> {
> "isMultiLine": true,
> "@type": "TextInput",
> "id": "IssueComment",
> "isRequired": false
> }
> ],
> "actions": [
> {
> "name": "Comment",
> "@type": "HttpPOST",
> "target": "https://api.github.com",
> "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"CodeHubApp/CodeHub\",\n\"issueId\": 482,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
> }
> ]
> },
> {
> "targets": [
> {
> "os": "default",
> "uri": "https://github.com/CodeHubApp/CodeHub/pull/482#issuecomment-440545748"
> }
> ],
> "@type": "OpenUri",
> "name": "View on GitHub"
> },
> {
> "name": "Unsubscribe",
> "@type": "HttpPOST",
> "target": "https://api.github.com",
> "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 344323389\n}"
> }
> ],
> "themeColor": "26292E"
> }
> ]
> ―
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

―

**Comment by TupleNx** [comment]
搞毛，不睡觉乱发什么？

**Pull request closed without merging**
